spring:

  # PostgreSQL
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/tenjudge
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # Redis
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      lettuce:
        pool:
          max-active: 16      # 最大连接数
          max-idle: 8       # 最大空闲连接
          min-idle: 0        # 最小空闲连接
          max-wait: 1000ms    # 连接等待时间

  # RabbitMQ
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: tenjudge
    username: admin
    password: "051223"
    listener:
      simple:
        prefetch: 1

# MyBatis
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mappers/**/*.xml

sa-token:
  token-name: tenjudge-token # token 名称（同时也是 cookie 名称）
  timeout: 3600 # token 有效期（单位：秒） 默认30天，-1 代表永久有效 （同时作为 redis 中权限信息的过期时间）
  active-timeout: -1 # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结

minio:
  endpoint: http://127.0.0.1:9000
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket-name: tenjudge

# App
app:
  auth:
    role-cache-expire: 3600 # 角色权限缓存过期时间（单位：秒）
  file-storage:
    temp: "/Users/shaun/Workspace/Data/TenJudge/temp"