spring:

  # PostgreSQL
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/tenjudge
    username: postgres
    password: "051223"

  # Redis
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      lettuce:
        pool:
          max-active: 16      # 最大连接数
          max-idle: 8       # 最大空闲连接
          min-idle: 0        # 最小空闲连接
          max-wait: 1000ms    # 连接等待时间

  # RabbitMQ
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: tenjudge
    username: admin
    password: "051223"
    listener:
      simple:
        prefetch: 1



# MinIO
minio:
  endpoint: http://127.0.0.1:9000
  access-key: root
  secret-key: 12345678
  bucket-name: tenjudge

# App
app:
  auth:
    super-admin-username: admin # 默认超级管理员用户名
    super-admin-password: "12345678" # 默认超级管理员密码
    super-admin-email: "super_admin@tenjudge.com" # 默认超级管理员邮箱
  file-storage:
    temp: "/Users/shaun/Workspace/Data/TenJudge/temp"
  cache-ttl:
    user-role: 3600s # 角色权限缓存 TTL
    problem: 5h # 题目元数据缓存 TTL
    problem-tags: 5h # 题目标签缓存 TTL
    problem-list: 30s # 公开题目分页列表缓存 TTL
    contest-problem: 5h # 比赛题目编排缓存 TTL
    contest-detail: 30s # 比赛详情聚合缓存 TTL
    contest-list: 30s # 比赛分页列表公共数据缓存 TTL
    null-value: 30s # 空值缓存 TTL，用于防止缓存穿透
    spring-cache-default: 1h # Spring Cache 默认 TTL
    board: 24h # 榜单缓存 TTL
