spring:

  # File
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  # PostgreSQL
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tenjudge
    username: postgres
    password: "051223"

  # Redis
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      lettuce:
        pool:
          max-active: 16      # 最大连接数
          max-idle: 8       # 最大空闲连接
          min-idle: 0        # 最小空闲连接
          max-wait: 1000ms    # 连接等待时间

# MyBatis
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mappers/**/*.xml

sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: tenjudge-token
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 600
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1

# App
app:
  file-storage:
    data: "/Users/shaun/Workspace/Data/TenJudge/data"
    temp: "/Users/shaun/Workspace/Data/TenJudge/temp"