package io.github.yush1x.tenjudge.server.common;

import lombok.Getter;

import java.util.Arrays;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;

// Generated by GPT-5.3-Codex

@Getter
public enum Language {

    CPP("cpp", "cpp"),
    PYTHON("python", "py");

    private final String name;
    private final String suffix;

    Language(String name, String suffix) {
        this.name = name;
        this.suffix = suffix;
    }

    // Cache for O(1) name -> suffix lookup.
    private static final Map<String, String> LANGUAGE_SUFFIX_MAP = Arrays.stream(Language.values())
            .collect(Collectors.toMap(Language::getName, Language::getSuffix, (left, right) -> left));

    // Cache for O(1) membership checks.
    private static final Set<String> LANGUAGE_NAME_SET = LANGUAGE_SUFFIX_MAP.keySet();

    public static String getSuffixByName(String name) {
        if (name == null) {
            return null;
        }
        return LANGUAGE_SUFFIX_MAP.get(name);
    }

    public static boolean contains(String name) {
        return name != null && LANGUAGE_NAME_SET.contains(name);
    }
}
